version: '0.1'

services:
  frontend:
      build:
        context: ./frontend
        args:
          - NODE_ENV=development
      environment:
        - NODE_ENV=development
      tty: true
      ports:
        - '19006:19006'
        - '19001:19001'
        - '19002:19002'
      healthcheck:
        disable: true
      volumes:
      - type: bind
        source: ./frontend/react-native/
        target: /opt/react-native-app/
  backend:
      build:
        context: ./backend
      ports:
       - '5000:5000'
      volumes:
      - type: bind
        source: ./backend/flask-python
        target: /opt/flask-python
volumes:
  myapp: